/**
 * @aro-context-marker
 * AI READABILITY NOTE: Auto-fix module for ARO audit issues.
 * Applies safe, reversible fixes for each blind spot category.
 */

import fs from "fs";
import path from "path";
import { Branding } from "./constants";
import { AROContext } from "./types";
import { run as runRules } from "./rules";
import { run as runRefactor } from "./refactor";

const FIXABLE_PATTERNS = [
  "Missing README",
  "No dedicated Agent instructions",
  "large files detected",
];

/** Returns true if a blind spot has an available auto-fix. */
export function canFix(blindSpot: string): boolean {
  return FIXABLE_PATTERNS.some((p) => blindSpot.includes(p));
}

/**
 * Applies all available auto-fixes based on the audit context.
 * Safe fixes only — security issues and structural debt require manual review.
 */
export async function run(context: AROContext): Promise<void> {
  const projectPath = process.cwd();
  const applied: string[] = [];
  const skipped: string[] = [];

  console.log(Branding.border(""));
  console.log(Branding.cyan.bold("🔧 ARO Auto-Fix"));
  console.log(Branding.border(""));

  for (const spot of context.blindSpots) {
    if (spot.includes("Missing README")) {
      const readmePath = path.join(projectPath, "README.md");
      fs.writeFileSync(readmePath, generateReadme(context));
      applied.push("Created README.md");
    } else if (spot.includes("No dedicated Agent instructions")) {
      runRules();
      applied.push(
        "Generated .cursorrules, .windsurfrules, AI-CONSTITUTION.md, CLAUDE.md, copilot-instructions.md",
      );
    } else if (spot.includes("large files detected")) {
      await runRefactor({ apply: true });
      applied.push("Applied refactoring to large files (see ARO-REFACTOR-PLAN.md)");
    } else {
      skipped.push(spot);
    }
  }

  if (applied.length > 0) {
    console.log(Branding.success("\n✅ Fixed:"));
    applied.forEach((fix) => console.log(Branding.gray(`  • ${fix}`)));
  }

  if (skipped.length > 0) {
    console.log(Branding.warning("\n⚠️  Requires manual attention:"));
    skipped.forEach((s) => console.log(Branding.gray(`  • ${s}`)));
  }

  if (applied.length === 0 && skipped.length === 0) {
    console.log(
      Branding.success(
        "\n✅ Nothing to fix — your project is already optimized!",
      ),
    );
  } else if (applied.length > 0) {
    console.log(Branding.cyan("\n💡 Run aro audit again to verify your score."));
  }

  console.log(Branding.border(""));
}

/** Generates a minimal but AI-ready README from project context. */
export function generateReadme(context: AROContext): string {
  const techList =
    context.techStack.length > 0
      ? context.techStack.map((t) => `- ${t}`).join("\n")
      : "- Node.js";

  return `# ${context.projectName}

## Installation

\`\`\`bash
npm install ${context.projectName}
\`\`\`

## Usage

\`\`\`bash
# Example usage
\`\`\`

## Configuration

Refer to the project documentation for available options and flags.

## Tech Stack

${techList}

---
*Generated by ARO (Agent Readability Optimizer)*
`;
}
